In [2]:
import pandas as pd

# Read file contents and store them in pandas dataframe with required headers
headers = ['baseball_game_on_TV', 'George_watches_TV', 'out_of_cat_food', 'George_feeds_cat']
data = []

with open('training_data.txt', 'r') as f:
    line = f.readline().rstrip('\n')
    data.append(line.split('     ')[1:])
    while line:
        line = f.readline().rstrip('\n')
        if line != "":
            data.append(line.split('     ')[1:])

df = pd.DataFrame(data, columns = headers)
df

    baseball_game_on_TV George_watches_TV out_of_cat_food George_feeds_cat
0                     0                 0               1                1
1                     0                 0               0                1
2                     0                 0               0                1
3                     0                 0               0                1
4                     0                 0               0                1
..                  ...               ...             ...              ...
360                   0                 0               1                0
361                   0                 0               0                1
362                   1                 0               1                0
363                   0                 0               0                1
364                   0                 0               0                1

[365 rows x 4 columns]

In [3]:
# Calculating prior probability of Baseball_game_on_TV
count_true = 0
tot_count = 0

for i in df['baseball_game_on_TV'] == '1':
    if i == True:
        count_true += 1
    tot_count += 1

print(count_true, tot_count)
P1 = count_true/tot_count
print("P(baseball_game_on_TV) =", P1)

111 365
P(baseball_game_on_TV) = 0.3041095890410959

In [5]:
# Function to calculate the prior probabilities
def calc_prior_prob(df, var_name):
    count_true = 0
    tot_count = 0
    p1 = len(df[df[var_name] == '1'])/ len(df[var_name])
    
    return p1

p1 = calc_prior_prob(df, 'baseball_game_on_TV')
print('P(baseball_game_on_TV) =', p1)
p2 =  calc_prior_prob(df, 'out_of_cat_food')
print('P(out_of_cat_food) =', p2)
print('P(George_feeds_cat) =', calc_prior_prob(df, 'George_feeds_cat'))

P(baseball_game_on_TV) = 0.3041095890410959
P(out_of_cat_food) = 0.16986301369863013
P(George_feeds_cat) = 0.7561643835616438

In [88]:
df[df['baseball_game_on_TV'] == '1']
df[(df['baseball_game_on_TV'] == '1') & (df['George_watches_TV'] == '1')]

    baseball_game_on_TV George_watches_TV out_of_cat_food George_feeds_cat
7                     1                 1               1                0
8                     1                 1               0                0
19                    1                 1               0                0
22                    1                 1               0                1
25                    1                 1               0                1
..                  ...               ...             ...              ...
339                   1                 1               0                0
349                   1                 1               1                0
354                   1                 1               0                1
357                   1                 1               0                1
359                   1                 1               0                1

[103 rows x 4 columns]

In [89]:
def calc_cond_prob(df, var_name, given_var_name):
    p1 = (len(df[(df[given_var_name] == '1') & (df[var_name] == '1')]))/(len(df[df[given_var_name] == '1']))
    p2 = (len(df[(df[given_var_name] == '0') & (df[var_name] == '1')]))/(len(df[df[given_var_name] == '0']))
    return p1, p2

p3, p4 = calc_cond_prob(df, 'George_watches_TV', 'baseball_game_on_TV')
print('P(George_watches_TV = True | baseball_game_on_TV = True) =', p3, '\nP(George_watches_TV = False | baseball_game_on_TV = True) =', 1-p3)
print('P(George_watches_TV = True | baseball_game_on_TV = False) =', p4, '\nP(George_watches_TV = False | baseball_game_on_TV = False) =', 1-p4)

P(George_watches_TV = True | baseball_game_on_TV = True) = 0.9279279279279279
P(George_watches_TV = False | baseball_game_on_TV = True) = 0.07207207207207211
P(George_watches_TV = True | baseball_game_on_TV = False) = 0.11811023622047244
P(George_watches_TV = False | baseball_game_on_TV = False) = 0.8818897637795275

In [92]:
def calc_cond_prob(df, var_name, given_var_name1, given_var_name2 = 'any'):
    if given_var_name2 == 'any':
        p1 = (len(df[(df[given_var_name1] == '1') & (df[var_name] == '1')]))/(len(df[df[given_var_name1] == '1']))
        p2 = (len(df[(df[given_var_name1] == '0') & (df[var_name] == '1')]))/(len(df[df[given_var_name1] == '0']))
        return p1, p2
    else:
        p1 = (len(df[(df[given_var_name1] == '1') & (df[given_var_name2] == '1') & (df[var_name] == '1')]))/(len(df[(df[given_var_name1] == '1') & (df[given_var_name2] == '1')]))
        p2 = (len(df[(df[given_var_name1] == '0') & (df[given_var_name2] == '1') & (df[var_name] == '1')]))/(len(df[(df[given_var_name1] == '0') & (df[given_var_name2] == '1')]))
        p3 = (len(df[(df[given_var_name1] == '1') & (df[given_var_name2] == '0') & (df[var_name] == '1')]))/(len(df[(df[given_var_name1] == '1') & (df[given_var_name2] == '0')]))
        p4 = (len(df[(df[given_var_name1] == '0') & (df[given_var_name2] == '0') & (df[var_name] == '1')]))/(len(df[(df[given_var_name1] == '0') & (df[given_var_name2] == '0')]))
        return p1, p2, p3, p4
    
p3, p4 = calc_cond_prob(df, 'George_watches_TV', 'baseball_game_on_TV')
print('P(George_watches_TV = True | baseball_game_on_TV = True) =', p3, '\nP(George_watches_TV = False | baseball_game_on_TV = True) =', 1-p3)
print('P(George_watches_TV = True | baseball_game_on_TV = False) =', p4, '\nP(George_watches_TV = False | baseball_game_on_TV = False) =', 1-p4)
print('\n')

p5, p6, p7, p8 = calc_cond_prob(df, 'George_feeds_cat', 'George_watches_TV', 'out_of_cat_food')
print('P(George_feeds_cat = True | (George_watches_TV = True , out_of_cat_food = True))) = ', p5)
print('P(George_feeds_cat = False | (George_watches_TV = True , out_of_cat_food = True))) = ', 1-p5)
print('P(George_feeds_cat = True | (George_watches_TV = False , out_of_cat_food = True))) = ', p6)
print('P(George_feeds_cat = False | (George_watches_TV = False , out_of_cat_food = True))) = ', 1-p6)
print('P(George_feeds_cat = True | (George_watches_TV = True , out_of_cat_food = False))) = ', p7)
print('P(George_feeds_cat = False | (George_watches_TV = True , out_of_cat_food = False))) = ', 1-p7)
print('P(George_feeds_cat = True | (George_watches_TV = False , out_of_cat_food = False))) = ', p8)
print('P(George_feeds_cat = False | (George_watches_TV = False , out_of_cat_food = False))) = ', 1-p8)

print(p5, p6, p7, p8)

P(George_watches_TV = True | baseball_game_on_TV = True) = 0.9279279279279279
P(George_watches_TV = False | baseball_game_on_TV = True) = 0.07207207207207211
P(George_watches_TV = True | baseball_game_on_TV = False) = 0.11811023622047244
P(George_watches_TV = False | baseball_game_on_TV = False) = 0.8818897637795275


P(George_feeds_cat = True | (George_watches_TV = True , out_of_cat_food = True))) =  0.041666666666666664
P(George_feeds_cat = False | (George_watches_TV = True , out_of_cat_food = True))) =  0.9583333333333334
P(George_feeds_cat = True | (George_watches_TV = False , out_of_cat_food = True))) =  0.3157894736842105
P(George_feeds_cat = False | (George_watches_TV = False , out_of_cat_food = True))) =  0.6842105263157895
P(George_feeds_cat = True | (George_watches_TV = True , out_of_cat_food = False))) =  0.7064220183486238
P(George_feeds_cat = False | (George_watches_TV = True , out_of_cat_food = False))) =  0.29357798165137616
P(George_feeds_cat = True | (George_watches_TV = False , out_of_cat_food = False))) =  0.9587628865979382
P(George_feeds_cat = False | (George_watches_TV = False , out_of_cat_food = False))) =  0.04123711340206182
0.041666666666666664 0.3157894736842105 0.7064220183486238 0.9587628865979382

In [97]:
# Function to calculate the prior probabilities
def calc_prior_prob(df, var_name):
    count_true = 0
    tot_count = 0
    p1 = len(df[df[var_name] == '1'])/ len(df[var_name])
    
    return p1

def calc_cond_prob(df, var_name, given_var_name1, given_var_name2 = 'any'):
    if given_var_name2 == 'any':
        p1 = (len(df[(df[given_var_name1] == '1') & (df[var_name] == '1')]))/(len(df[df[given_var_name1] == '1']))
        p2 = (len(df[(df[given_var_name1] == '0') & (df[var_name] == '1')]))/(len(df[df[given_var_name1] == '0']))
        return p1, p2
    else:
        p1 = (len(df[(df[given_var_name1] == '1') & (df[given_var_name2] == '1') & (df[var_name] == '1')]))/(len(df[(df[given_var_name1] == '1') & (df[given_var_name2] == '1')]))
        p2 = (len(df[(df[given_var_name1] == '0') & (df[given_var_name2] == '1') & (df[var_name] == '1')]))/(len(df[(df[given_var_name1] == '0') & (df[given_var_name2] == '1')]))
        p3 = (len(df[(df[given_var_name1] == '1') & (df[given_var_name2] == '0') & (df[var_name] == '1')]))/(len(df[(df[given_var_name1] == '1') & (df[given_var_name2] == '0')]))
        p4 = (len(df[(df[given_var_name1] == '0') & (df[given_var_name2] == '0') & (df[var_name] == '1')]))/(len(df[(df[given_var_name1] == '0') & (df[given_var_name2] == '0')]))
        return p1, p2, p3, p4


p1 = calc_prior_prob(df, 'baseball_game_on_TV')
print('P(baseball_game_on_TV) =', p1)
p2 =  calc_prior_prob(df, 'out_of_cat_food')
print('P(out_of_cat_food) =', p2)

p3, p4 = calc_cond_prob(df, 'George_watches_TV', 'baseball_game_on_TV')
print('P(George_watches_TV = True | baseball_game_on_TV = True) =', p3, '\nP(George_watches_TV = False | baseball_game_on_TV = True) =', 1-p3)
print('P(George_watches_TV = True | baseball_game_on_TV = False) =', p4, '\nP(George_watches_TV = False | baseball_game_on_TV = False) =', 1-p4)

p5, p6, p7, p8 = calc_cond_prob(df, 'George_feeds_cat', 'George_watches_TV', 'out_of_cat_food')
print('P(George_feeds_cat = True | (George_watches_TV = True , out_of_cat_food = True))) = ', p5)
print('P(George_feeds_cat = False | (George_watches_TV = True , out_of_cat_food = True))) = ', 1-p5)
print('P(George_feeds_cat = True | (George_watches_TV = False , out_of_cat_food = True))) = ', p6)
print('P(George_feeds_cat = False | (George_watches_TV = False , out_of_cat_food = True))) = ', 1-p6)
print('P(George_feeds_cat = True | (George_watches_TV = True , out_of_cat_food = False))) = ', p7)
print('P(George_feeds_cat = False | (George_watches_TV = True , out_of_cat_food = False))) = ', 1-p7)
print('P(George_feeds_cat = True | (George_watches_TV = False , out_of_cat_food = False))) = ', p8)
print('P(George_feeds_cat = False | (George_watches_TV = False , out_of_cat_food = False))) = ', 1-p8)

P(baseball_game_on_TV) = 0.3041095890410959
P(out_of_cat_food) = 0.16986301369863013
P(George_watches_TV = True | baseball_game_on_TV = True) = 0.9279279279279279
P(George_watches_TV = False | baseball_game_on_TV = True) = 0.07207207207207211
P(George_watches_TV = True | baseball_game_on_TV = False) = 0.11811023622047244
P(George_watches_TV = False | baseball_game_on_TV = False) = 0.8818897637795275
P(George_feeds_cat = True | (George_watches_TV = True , out_of_cat_food = True))) =  0.041666666666666664
P(George_feeds_cat = False | (George_watches_TV = True , out_of_cat_food = True))) =  0.9583333333333334
P(George_feeds_cat = True | (George_watches_TV = False , out_of_cat_food = True))) =  0.3157894736842105
P(George_feeds_cat = False | (George_watches_TV = False , out_of_cat_food = True))) =  0.6842105263157895
P(George_feeds_cat = True | (George_watches_TV = True , out_of_cat_food = False))) =  0.7064220183486238
P(George_feeds_cat = False | (George_watches_TV = True , out_of_cat_food = False))) =  0.29357798165137616
P(George_feeds_cat = True | (George_watches_TV = False , out_of_cat_food = False))) =  0.9587628865979382
P(George_feeds_cat = False | (George_watches_TV = False , out_of_cat_food = False))) =  0.04123711340206182